// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelItineraryWebsite2.Data;

#nullable disable

namespace TravelItineraryWebsite2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250212123908_remigration")]
    partial class remigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUserItinerary", b =>
                {
                    b.Property<int>("ItinerariesId")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ItinerariesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ApplicationUserItinerary");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "92fc0620-db8e-4623-bc6d-27dcded5f56f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "349e9614-1da2-4b78-b815-8de34d84ac17",
                            Email = "titus@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Titus",
                            LastName = "Cheng",
                            LockoutEnabled = false,
                            NormalizedEmail = "TITUS@LOCALHOST.COM",
                            NormalizedUserName = "TITUS@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGOOI7TCtPr7Gp95PI/5+e+i95S8iR5pMUv1bNcRrquGEwHlcoyJV2W/1dtvupUNkQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2c032b6d-c374-4ae2-960b-00c960804891",
                            TwoFactorEnabled = false,
                            UserName = "titus@localhost.com"
                        },
                        new
                        {
                            Id = "66872a47-cc8b-483a-bffd-4fe19ae17124",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "467697b3-1f05-48b1-96cf-8f394eb1105e",
                            Email = "tim@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Tim",
                            LastName = "Cheng",
                            LockoutEnabled = false,
                            NormalizedEmail = "TIM@LOCALHOST.COM",
                            NormalizedUserName = "TIM@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENXqQ4BeiRX9QaO/0d37ABlfqkwBs7KqF18TARqgMDblmiy8lSji0Edp2KSGQYAOqA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ef1cc8c5-f56a-4022-90dd-2041156f7248",
                            TwoFactorEnabled = false,
                            UserName = "tim@localhost.com"
                        });
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Domain.ApplicationUserItinerary", b =>
                {
                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationUserId", "ItineraryId");

                    b.HasIndex("ItineraryId");

                    b.ToTable("ApplicationUserItineraries");

                    b.HasData(
                        new
                        {
                            ApplicationUserId = "92fc0620-db8e-4623-bc6d-27dcded5f56f",
                            ItineraryId = 1
                        },
                        new
                        {
                            ApplicationUserId = "66872a47-cc8b-483a-bffd-4fe19ae17124",
                            ItineraryId = 1
                        },
                        new
                        {
                            ApplicationUserId = "66872a47-cc8b-483a-bffd-4fe19ae17124",
                            ItineraryId = 2
                        },
                        new
                        {
                            ApplicationUserId = "66872a47-cc8b-483a-bffd-4fe19ae17124",
                            ItineraryId = 3
                        });
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Domain.Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Itinerary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "92fc0620-db8e-4623-bc6d-27dcded5f56f",
                            CreatedByName = "Titus",
                            DateCreated = new DateTime(2025, 2, 12, 20, 39, 6, 738, DateTimeKind.Local).AddTicks(497),
                            DateUpdated = new DateTime(2025, 2, 12, 20, 39, 6, 738, DateTimeKind.Local).AddTicks(503),
                            EndDate = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hong Kong and Shenzhen Trip",
                            StartDate = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "92fc0620-db8e-4623-bc6d-27dcded5f56f",
                            UpdatedByName = "Titus"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "66872a47-cc8b-483a-bffd-4fe19ae17124",
                            CreatedByName = "Tim",
                            DateCreated = new DateTime(2025, 2, 12, 20, 39, 6, 738, DateTimeKind.Local).AddTicks(508),
                            DateUpdated = new DateTime(2025, 2, 12, 20, 39, 6, 738, DateTimeKind.Local).AddTicks(508),
                            EndDate = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Osaka Trip",
                            StartDate = new DateTime(2025, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "66872a47-cc8b-483a-bffd-4fe19ae17124",
                            UpdatedByName = "Tim"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "92fc0620-db8e-4623-bc6d-27dcded5f56f",
                            CreatedByName = "Titus",
                            DateCreated = new DateTime(2025, 2, 12, 20, 39, 6, 738, DateTimeKind.Local).AddTicks(512),
                            DateUpdated = new DateTime(2025, 2, 12, 20, 39, 6, 738, DateTimeKind.Local).AddTicks(513),
                            EndDate = new DateTime(2025, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Japan Winter Trip",
                            StartDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "92fc0620-db8e-4623-bc6d-27dcded5f56f",
                            UpdatedByName = "Titus"
                        });
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Domain.ItineraryDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ArrivalLocationId")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("ArrivalTime")
                        .HasColumnType("time");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartureLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalLocationId");

                    b.HasIndex("DepartureLocationId");

                    b.HasIndex("ItineraryId");

                    b.HasIndex("LocationId");

                    b.ToTable("ItineraryDetail");
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItineraryId")
                        .HasColumnType("int");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Lng")
                        .HasColumnType("float");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Victoria Harbour",
                            ItineraryId = 1,
                            Lat = 22.307445999999999,
                            Lng = 114.16771,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJR3bnzBMBBDQRrodrPnMlcVg"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mitsushima Shin-uchi",
                            ItineraryId = 2,
                            Lat = 34.733974000000003,
                            Lng = 135.582807,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJTexD3aHhAGARNrzMqjfQG6Y"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Shirakawa-go",
                            ItineraryId = 3,
                            Lat = 36.257796999999997,
                            Lng = 136.90619799999999,
                            LocationType = 2,
                            Name = "",
                            PlaceId = "ChIJ5yW_trBx-F8R-AVYnbtRxcwY"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Lau Sum Kee",
                            ItineraryId = 1,
                            Lat = 22.331783000000001,
                            Lng = 114.163192,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJvxd8mOcBBDQRSoZgKiql49A"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Ying Kee",
                            ItineraryId = 1,
                            Lat = 22.285088999999999,
                            Lng = 114.142386,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJJzqTNYf_AzQRwKZRoDRERbw"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Shinhotaka Ropeway",
                            ItineraryId = 3,
                            Lat = 36.285792000000001,
                            Lng = 137.57526200000001,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJLUAe875PHWARkR1e5ffwR9k"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Unotake Kasu Udon",
                            ItineraryId = 2,
                            Lat = 34.670552000000001,
                            Lng = 135.499302,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJhfXfdxHnAGARxQbdzydTMTc"
                        },
                        new
                        {
                            Id = 8,
                            Address = "BEST WESTERN PLUS Hotel Hong Kong",
                            ItineraryId = 1,
                            Lat = 22.287279999999999,
                            Lng = 114.139121,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJewz8QYH_AzQRzRa9Gq-0NsE"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Centrage Ark Ueshio",
                            ItineraryId = 2,
                            Lat = 34.663462000000003,
                            Lng = 135.51678999999999,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJCdMda1DnAGARSFh3OgTKhFk"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Onyado Yuinosho",
                            ItineraryId = 3,
                            Lat = 36.277239000000002,
                            Lng = 136.902331,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJvXvOjU9x-F8RAWDVsroNuBg"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Hong Kong International Airport",
                            ItineraryId = 1,
                            Lat = 22.313473999999999,
                            Lng = 113.91372800000001,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJncZGzPPiAzQRnjaSGIKQ9fk"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Osaka Station",
                            ItineraryId = 2,
                            Lat = 34.702485000000003,
                            Lng = 135.49595099999999,
                            LocationType = 1,
                            Name = "",
                            PlaceId = "ChIJC6fjlY3mAGARSshZ6CLIrhs"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Hong Kong",
                            ItineraryId = 1,
                            Lat = 22.319303999999999,
                            Lng = 114.16936099999999,
                            LocationType = 2,
                            Name = "",
                            PlaceId = "ChIJD5gyo-3iAzQRfMnq27qzivA"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Osaka",
                            ItineraryId = 2,
                            Lat = 34.693725000000001,
                            Lng = 135.50225399999999,
                            LocationType = 2,
                            Name = "",
                            PlaceId = "ChIJ4eIGNFXmAGAR5y9q5G7BW8U"
                        });
                });

            modelBuilder.Entity("ApplicationUserItinerary", b =>
                {
                    b.HasOne("TravelItineraryWebsite2.Domain.Itinerary", null)
                        .WithMany()
                        .HasForeignKey("ItinerariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelItineraryWebsite2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TravelItineraryWebsite2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TravelItineraryWebsite2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelItineraryWebsite2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TravelItineraryWebsite2.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Domain.ApplicationUserItinerary", b =>
                {
                    b.HasOne("TravelItineraryWebsite2.Data.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelItineraryWebsite2.Domain.Itinerary", "Itinerary")
                        .WithMany()
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Domain.ItineraryDetail", b =>
                {
                    b.HasOne("TravelItineraryWebsite2.Domain.Location", "ArrivalLocation")
                        .WithMany()
                        .HasForeignKey("ArrivalLocationId");

                    b.HasOne("TravelItineraryWebsite2.Domain.Location", "DepartureLocation")
                        .WithMany()
                        .HasForeignKey("DepartureLocationId");

                    b.HasOne("TravelItineraryWebsite2.Domain.Itinerary", "Itinerary")
                        .WithMany("Details")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelItineraryWebsite2.Domain.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("ArrivalLocation");

                    b.Navigation("DepartureLocation");

                    b.Navigation("Itinerary");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Domain.Location", b =>
                {
                    b.HasOne("TravelItineraryWebsite2.Domain.Itinerary", "Itinerary")
                        .WithMany()
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("TravelItineraryWebsite2.Domain.Itinerary", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
